org: jhon64
app: mi-primer-projec
service: aws-node-http-api-project
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
#      Resource:

functions:
  addTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /task
          method: post
resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST #que nos cobre por perticion
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    usersRestaurant:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersRestaurant
        BillingMode: PAY_PER_REQUEST #que nos cobre por perticion
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
